module.exports = {
  ////// CONFIGURATION TEMPLATE: uncomment desired lines to override default config.
  ////// While all lines are commented, config will not change anything.
  toolbar: {
    items: [
      "fullScreen",
      "undo",
      "redo",
      "|",
      "heading",
      "|",
      "alignment",
      "indent",
      "outdent",
      "|",
      // 'fontFamily',
      // 'fontSize',
      "fontColor",
      "bold",
      "italic",
      "underline",
      "code",
      "link",
      "|",
      // "specialCharacters",
      "blockQuote",
      "horizontalLine",
      "bulletedList",
      "numberedList",
      "insertTable",
      "|",
      "insertImage",
      "mediaEmbed",
      "strapiMediaLib",
      "htmlEmbed",
      "codeBlock",
    ],
    shouldNotGroupWhenFull: false,
  },
};
